{"name": "test_check_from_name[test_data6]", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "test_data = {'input_data': 'q=000000000000', 'latitude': '41.7156479', 'longitude': '44.7465634'}\n\n    @allure.description(\"test_check_from_name\")\n    @pytest.mark.parametrize(\"test_data\", data_file(file_path=\"utils/data_for_searching_by_name.json\"))\n    def test_check_from_name(test_data):\n    \n        print(f\"\\nlatitude - {test_data['latitude']}\")\n        print(f\"\\nlongitude - {test_data['longitude']}\")  # <class 'dict'>\n    \n>       result = NominatimApi().search(query=test_data['input_data'])[0]  # <class 'dict'>\nE       IndexError: list index out of range\n\ntests/test_nominatim.py:15: IndexError"}, "description": "test_check_from_name", "steps": [{"name": "GET", "status": "passed", "start": 1689950223452, "stop": 1689950223945}], "attachments": [{"name": "stdout", "source": "49af3baa-9e03-4037-b549-bcef4a94702e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_data", "value": "{'input_data': 'q=000000000000', 'latitude': '41.7156479', 'longitude': '44.7465634'}"}], "start": 1689950223452, "stop": 1689950223946, "uuid": "90dd8da7-3011-4e7c-940b-6ae699cae893", "historyId": "10333a2282d50c49c0d4c37c7f0d913e", "testCaseId": "9a2d760b2d78affa18278650333d8a49", "fullName": "tests.test_nominatim#test_check_from_name", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_nominatim"}, {"name": "host", "value": "kochetova"}, {"name": "thread", "value": "2980166-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_nominatim"}]}